name: CI - Build and Test SpendFlow Utility

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build SpendFlow Executable
        run: gcc SpendFlow.c GUI.c GUI_inputs.c users.c budget_calculation.c transaction_helpers.c sortHistory.c addtransaction.c -o SpendFlow

      - name: Upload SpendFlow Executable
        uses: actions/upload-artifact@v4
        with:
          name: SpendFlow
          path: ./SpendFlow

      - name: Build Tests
        run: gcc -o ctest --coverage SpendFlow.c GUI.c GUI_inputs.c users.c budget_calculation.c transaction_helpers.c sortHistory.c addtransaction.c

      - name: Run Tests
        run: ./test_script > test_results.txt

      - name: Generate Coverage Reports
        run: |
          gcov SpendFlow.c
          gcov GUI.c
          gcov GUI_inputs.c
          gcov users.c
          gcov budget_calculation.c
          gcov transaction_helpers.c
          gcov sortHistory.c
          gcov addtransaction.c

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./test_results.txt

      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v4
        with:
          name: Coverage Reports
          path: |
            SpendFlow.c.gcov
            GUI.c.gcov
            GUI_inputs.c.gcov
            users.c.gcov
            budget_calculation.c.gcov
            transaction_helpers.c.gcov
            sortHistory.c.gcov
            addtransaction.c.gcov

